### PR TITLE
Developer

### PR DESCRIPTION
**Pull request by Ayyappa1997**

### CODE REVIEW

**Review by NavakumarHCL — COMMENTED** [review]
Hey Ayyappa can you do it by own instead of copying from internet completely.. :) This exercise is given to practice the coding also.. Can you create a dotnet project with simple calculator functionalities?

**Comment by NavakumarHCL** [comment]
And good that you have done a Git commit and a PR.

**Comment by Ayyappa1997** [comment]
Hi Nava,
Created calculator as  asp.net web application(web forms).Thanks

**Comment by Ayyappa1997** [comment]
Created new pull request

**Pull request closed without merging**
